### PR TITLE
Book of remeberance

### PR DESCRIPTION
**Pull request by hotnuts21**
Changes made to mirador. Built version.

### CODE REVIEW

**Comment by glenrobson** [comment]
hopefully thats merged successfully. going to deploy it now

**Comment by hotnuts21** [comment]
Looking good and errors going into the log service :-)

Your on Firefox ;-)
Testing starting at 9:30 in the morning.

Paul

**Comment by glenrobson** [comment]
thats good news apart from I chose the wrong translation strings to merge so re-deploying now. Hopefully you'll see less errors in a sec.

**Comment by hotnuts21** [comment]
OK let me know when to test again

**Comment by glenrobson** [comment]
Do you know if the following is required:

"Object Metadata": "something here"

in the translation.json? it seems to make it invalid json I assume due to the space.

Cheers

Glen

**Comment by hotnuts21** [comment]
That should be valid, might be missing a , at end of line?

Anyway it's not needed for this. It's the I button that opens the metadata
panel but i have hidden it. So it can go for now, but needs to be there
long term.

**Comment by hotnuts21** [comment]
Tool
http://jsonlint.com/

**Comment by glenrobson** [comment]
it says its valid so I may just leave it. Only invalid on firefox. 

Glen

**Pull request merged**
